ALTER TABLE `organisations` ADD `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `importID`;
ALTER TABLE `projects` ADD `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `importID`;

ALTER TABLE `organisation-follow` CHANGE `since` `since` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `project-follow` CHANGE `since` `since` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;